### PR TITLE
Move the signing key to files/default

### PR DESCRIPTION
**Pull request by ziggythehamster**
This is where Chef expects the key to be.

### CODE REVIEW

**Comment by st-isidore-de-seville** [comment]
@ziggythehamster, just out of curiosity, having signing key in `files` passed all test cases.  What is a test scenario where having the signing key just in `files` and not `files/default` fail?

**Comment by ziggythehamster** [comment]
Chef 11.18.12 dies because the file is not in the correct directory. It actually even tells you "didn't find the file in `files/debian-8.2`, `files/debian`, or `files/default`. DID find it in `files`", but then it throws an exception because `files` is not the correct place for it.

**Comment by st-isidore-de-seville** [comment]
Thanks for the clarification @ziggythehamster, I will ensure to test this against Chef 11 when doing this build.  Please give me a day or so to get this setup.

**Comment by st-isidore-de-seville** [comment]
@ziggythehamster I am going to go ahead and accept this but am going to refactor this cookbook based on st-isidore-de-seville/cookbook-apt-nginx and st-isidore-de-seville/cookbook-yum-nginx

**Pull request merged**
